name: skdesign

services:
    nginx:
        build:
            context: .
            dockerfile: docker-compose/nginx/Dockerfile
        volumes:
            - ./:/var/www/
            - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - php
            - mysql
        networks:
            - skdesign

    php:
        build:
            context: .
            dockerfile: docker-compose/php/Dockerfile
            args:
                localUid: 1000
                localGid: 1000
                localUser: ${DOCKER_USER}
        volumes:
            - ./:/var/www
        networks:
            - skdesign

    mysql:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: dev
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - skdesign

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 300M
        depends_on:
            - mysql
        ports:
            - "8082:80"
        networks:
            - skdesign

networks:
    skdesign:
        driver: bridge
